version = "1.0"

[main]
name.en = "Configuration panel"
name.fr = "Panneau de configuration"
services = ["__APP__", "nginx"]


[main.instance]
name.en = "Global settings"
name.fr = "Paramètres Globaux"

