#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2
id = "versitygw"
name = "Versity S3 Gateway"
description.en = "A High-Performance S3 Translation Service."
description.fr = "Passerelle S3 haute performance." 
version = "1.7.0~ynh1"

maintainers = ["otm33GH"]

[upstream]
license = "Apache-2.0"
website = "https://www.versity.com/products/versitygw/"
admindoc = "https://github.com/versity/versitygw/wiki"
code = "https://github.com/versity/versitygw"


[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["amd64","arm64"]
multi_instance = false
   
ldap = false
sso = false

disk = "150M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"


[resources]
    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/versity/versitygw/releases/download/v1.7.0/versitygw_v1.7.0_Linux_x86_64.tar.gz"
    amd64.sha256 = "dacec530fecaa8776feec0536998dd4bd78036e0d4db0da9b9189d96bb790e03"
    arm64.url = "https://github.com/versity/versitygw/releases/download/v1.7.0/versitygw_v1.7.0_Linux_arm64.tar.gz"
    arm64.sha256 = "5ef8d098e58b66171f2d8cd93dfcf44a7b3984d2e5710562ab1af6c884bc0a34"

    autoupdate.asset.amd64 = "^versitygw_v\\d+(\\.\\d+)+_Linux_x86_64\\.tar\\.gz$"
    autoupdate.asset.arm64 = "^versitygw_v\\d+(\\.\\d+)+_Linux_arm64\\.tar\\.gz$"
    autoupdate.strategy = "latest_github_release" 

    [resources.system_user]
	allow_email = true
    
    [resources.install_dir]
    [resources.data_dir]
    subdirs = ["datadir", "versioning", ".iam"]

    [resources.permissions]

    main.url = "/"
    main.auth_header = false

    [resources.ports]
    [resources.ports.ui]
