#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin_key=$(ynh_string_random --length=20)
admin_secret=$(ynh_string_random --length=40)
ynh_app_setting_set --app=$app --key=admin_key --value=$admin_key
ynh_app_setting_set --app=$app --key=admin_secret --value=$admin_secret

email_smtp_host=$(cat /etc/yunohost/current_host)
email_smtp_user="$app"
email_smtp_password="$mail_pwd"
email_smtp_port=587

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_setup_source --dest_dir="$install_dir"
mkdir "$install_dir/$app.d"
ynh_config_add --template="mygateway.conf" --destination="$install_dir/$app.d/mygateway.conf"

#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_config_add_nginx

ynh_config_add_systemd --service="$app" 

yunohost service add "$app" --description="Versity S3 Gateway" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

#ynh_systemctl --service="$app" --action="stop"
#systemctl reset-failed $app
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
