#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin_key=$(ynh_string_random --length=20)
admin_secret=$(ynh_string_random --length=40)
ynh_app_setting_set --app=$app --key=admin_key --value=$admin_key
ynh_app_setting_set --app=$app --key=admin_secret --value=$admin_secret

email_smtp_host=$(cat /etc/yunohost/current_host)
email_smtp_user="$app"
email_smtp_password="$mail_pwd"
email_smtp_port=587
pwd_reset=true
registration=true
retention=30
doc_storage_driver=$doc_storage_driver

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

npm install --global corepack@latest
corepack enable pnpm
corepack use pnpm@latest

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template=".env" --destination="$install_dir/.env"
ynh_config_add --template="papra.config.yaml" --destination="$install_dir/apps/papra-server/papra.config.yaml"

#=================================================
# INSTALLATION
#=================================================

pushd "$install_dir"
ynh_exec_as_app pnpm install 
ynh_exec_as_app pnpm -r build
ynh_exec_as_app mkdir -p apps/papra-server/public
ynh_exec_as_app cp -r apps/papra-client/dist/* apps/papra-server/public/
pnpm store prune
popd
chown -R $app:$app $install_dir



#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_config_add_nginx

ynh_config_add_systemd --service="$app" 

yunohost service add "$app" --description="Papra Docs" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
